### ISSUE TITLE
Unable to run it.

### ISSUE THREAD

**Issue by uhlhosting** [dnewcome/dub-siren#1]
➜  dub-siren-master  node server.js        

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kosmos/Downloads/dub-siren-master/server.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
➜  dub-siren-master

**Comment by uhlhosting** [comment]
➜  dub-siren-master  node server.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'sdlmixer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kosmos/Downloads/dub-siren-master/server.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
➜  dub-siren-master  npm install sdlmixer
npm WARN package.json dubsiren@0.0.1 No repository field.
npm WARN engine sdlmixer@0.0.9: wanted: {"node":"0.4.x"} (current: {"node":"0.10.35","npm":"1.4.28"})

> sdlmixer@0.0.9 preinstall /Users/kosmos/Downloads/dub-siren-master/node_modules/sdlmixer
> node-waf clean || true; node-waf configure build

sh: node-waf: command not found
sh: node-waf: command not found

npm ERR! sdlmixer@0.0.9 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the sdlmixer@0.0.9 preinstall script.
npm ERR! This is most likely a problem with the sdlmixer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || true; node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sdlmixer
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "sdlmixer"
npm ERR! cwd /Users/kosmos/Downloads/dub-siren-master
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
➜  dub-siren-master

**Comment by dnewcome** [comment]
I don't think node-sdlmixer is being maintained anymore. I submitted a patch updating the build to use gyp, but it still segfaults for me at runtime.

I filed this issue:
https://github.com/japj/node-sdlmixer/issues/20

node-sdlmixer worked really well in the past, but currently it seems to be broken.
